-- 税区分内訳カラムを sales テーブルに追加
ALTER TABLE sales ADD COLUMN IF NOT EXISTS tax8  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS tax10 INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS tax   INTEGER NOT NULL DEFAULT 0;
